name: deborah
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.3-alpha

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaru: ^0.3.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.3
  csv: ^5.0.1
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/resources/
